# 大型实例 52U96G 配置
name: "大型 52U96G"
instance_type: ecs.c6e.13xlarge
spot_strategy: SpotAsPriceGo
spot_duration: 0
spot_interruption_behavior: Stop
internet_max_bandwidth_out: 100
internet_charge_type: PayByTraffic
disk_size: 35
